# Generated by Django 4.2 on 2023-04-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='featured',
            new_name='featured_item',
        ),
    ]
