# Generated by Django 4.2 on 2023-04-24 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonAPI', '0006_cartorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cartorder',
            unique_together={('order', 'cart', 'user')},
        ),
    ]
