# Generated by Django 4.2 on 2023-04-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0007_cartorder_user_alter_cartorder_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
