# Generated by Django 4.2 on 2023-04-25 01:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonAPI', '0008_rename_price_menuitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menu_item', 'user')},
        ),
    ]
