# Generated by Django 4.2 on 2023-04-25 01:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonAPI', '0009_rename_menuitem_cart_menu_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_item',
            new_name='menuitem',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menuitem', 'user')},
        ),
    ]
